# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmail_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# pyuic5 -x cmail_new.ui -o design.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_cmail(object):
    def setupUi(self, Form_cmail):
        Form_cmail.setObjectName("Form_cmail")
        Form_cmail.resize(733, 417)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        Form_cmail.setFont(font)
        self.tabWidget_cmail = QtWidgets.QTabWidget(Form_cmail)
        self.tabWidget_cmail.setGeometry(QtCore.QRect(40, 30, 640, 360))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.tabWidget_cmail.setFont(font)
        self.tabWidget_cmail.setStyleSheet("QTabBar::tab { width: 100px; height: 25px; text-align: center; }")
        self.tabWidget_cmail.setObjectName("tabWidget_cmail")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.label_home = QtWidgets.QLabel(self.tab_home)
        self.label_home.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_home.setStyleSheet("border-image:url(\"C:/Users/bedir/PycharmProjects/CMail/images/home.jpg\");\n"
"border-radius:10px;")
        self.label_home.setText("")
        self.label_home.setObjectName("label_home")
        self.label_homeTitle = QtWidgets.QLabel(self.tab_home)
        self.label_homeTitle.setGeometry(QtCore.QRect(360, 10, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_homeTitle.setFont(font)
        self.label_homeTitle.setStyleSheet("color: rgba(255, 255, 255, 200);")
        self.label_homeTitle.setObjectName("label_homeTitle")
        self.label_homeAlpha = QtWidgets.QLabel(self.tab_home)
        self.label_homeAlpha.setGeometry(QtCore.QRect(249, 0, 381, 330))
        self.label_homeAlpha.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"border-radius: 10px;")
        self.label_homeAlpha.setText("")
        self.label_homeAlpha.setObjectName("label_homeAlpha")
        self.textBrowser_homeContent = QtWidgets.QTextBrowser(self.tab_home)
        self.textBrowser_homeContent.setEnabled(False)
        self.textBrowser_homeContent.setGeometry(QtCore.QRect(260, 50, 361, 261))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.textBrowser_homeContent.setFont(font)
        self.textBrowser_homeContent.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,242);")
        self.textBrowser_homeContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_homeContent.setObjectName("textBrowser_homeContent")
        self.label_home.raise_()
        self.label_homeAlpha.raise_()
        self.label_homeTitle.raise_()
        self.textBrowser_homeContent.raise_()
        self.tabWidget_cmail.addTab(self.tab_home, "")
        self.tab_cmail = QtWidgets.QWidget()
        self.tab_cmail.setObjectName("tab_cmail")
        self.label_cmail = QtWidgets.QLabel(self.tab_cmail)
        self.label_cmail.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_cmail.setStyleSheet("border-image:url(\"C:/Users/bedir/PycharmProjects/CMail/images/cmail.png\");\n"
"border-radius:10px;")
        self.label_cmail.setText("")
        self.label_cmail.setObjectName("label_cmail")
        self.pushButton_start = QtWidgets.QPushButton(self.tab_cmail)
        self.pushButton_start.setGeometry(QtCore.QRect(30, 220, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 15px;\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"    }")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.tab_cmail)
        self.pushButton_stop.setGeometry(QtCore.QRect(140, 220, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 15px;\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"    }")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_cmailAlpha = QtWidgets.QLabel(self.tab_cmail)
        self.label_cmailAlpha.setGeometry(QtCore.QRect(260, 0, 371, 331))
        self.label_cmailAlpha.setStyleSheet("background-color: rgba(0, 0, 0, 120);\n"
"border-radius: 10px;")
        self.label_cmailAlpha.setText("")
        self.label_cmailAlpha.setObjectName("label_cmailAlpha")
        self.lineEdit_mail = QtWidgets.QLineEdit(self.tab_cmail)
        self.lineEdit_mail.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.lineEdit_mail.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: white;\n"
"padding-bottom: 7px;\n"
"")
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_cmail)
        self.lineEdit_password.setGeometry(QtCore.QRect(40, 140, 171, 20))
        self.lineEdit_password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(46, 82, 101, 200);\n"
"color: white;\n"
"padding-bottom: 7px;\n"
"")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_checkMsg = QtWidgets.QLabel(self.tab_cmail)
        self.label_checkMsg.setGeometry(QtCore.QRect(40, 170, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_checkMsg.setFont(font)
        self.label_checkMsg.setStyleSheet("color: rgba(255, 255, 255, 255);")
        self.label_checkMsg.setObjectName("label_checkMsg")
        self.label_status = QtWidgets.QLabel(self.tab_cmail)
        self.label_status.setGeometry(QtCore.QRect(90, 280, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: rgba(255, 255, 255, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.label_cmailTitle = QtWidgets.QLabel(self.tab_cmail)
        self.label_cmailTitle.setGeometry(QtCore.QRect(40, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_cmailTitle.setFont(font)
        self.label_cmailTitle.setStyleSheet("color: white;\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 125, 0, 200);\n"
"padding-bottom: 7px;")
        self.label_cmailTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cmailTitle.setObjectName("label_cmailTitle")
        self.textBrowser_homeContent_2 = QtWidgets.QTextBrowser(self.tab_cmail)
        self.textBrowser_homeContent_2.setEnabled(False)
        self.textBrowser_homeContent_2.setGeometry(QtCore.QRect(270, 50, 351, 251))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.textBrowser_homeContent_2.setFont(font)
        self.textBrowser_homeContent_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgba(255,255,255,242);")
        self.textBrowser_homeContent_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_homeContent_2.setObjectName("textBrowser_homeContent_2")
        self.label_homeTitle_2 = QtWidgets.QLabel(self.tab_cmail)
        self.label_homeTitle_2.setGeometry(QtCore.QRect(380, 10, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_homeTitle_2.setFont(font)
        self.label_homeTitle_2.setStyleSheet("color: rgba(255, 255, 255, 200);")
        self.label_homeTitle_2.setObjectName("label_homeTitle_2")
        self.label_cmail.raise_()
        self.label_cmailAlpha.raise_()
        self.lineEdit_mail.raise_()
        self.lineEdit_password.raise_()
        self.label_checkMsg.raise_()
        self.label_status.raise_()
        self.pushButton_stop.raise_()
        self.pushButton_start.raise_()
        self.label_cmailTitle.raise_()
        self.textBrowser_homeContent_2.raise_()
        self.label_homeTitle_2.raise_()
        self.tabWidget_cmail.addTab(self.tab_cmail, "")
        self.tab_logs = QtWidgets.QWidget()
        self.tab_logs.setObjectName("tab_logs")
        self.label_logs = QtWidgets.QLabel(self.tab_logs)
        self.label_logs.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_logs.setStyleSheet("border-image:url(\"C:/Users/bedir/PycharmProjects/CMail/images/logs.png\");\n"
"border-radius:10px;")
        self.label_logs.setText("")
        self.label_logs.setObjectName("label_logs")
        self.label_logsAlpha = QtWidgets.QLabel(self.tab_logs)
        self.label_logsAlpha.setGeometry(QtCore.QRect(300, 0, 331, 331))
        self.label_logsAlpha.setStyleSheet("background-color:rgba(0,0,0,40);\n"
"border-radius:10px;")
        self.label_logsAlpha.setText("")
        self.label_logsAlpha.setObjectName("label_logsAlpha")
        self.pushButton_logsClear = QtWidgets.QPushButton(self.tab_logs)
        self.pushButton_logsClear.setGeometry(QtCore.QRect(420, 60, 151, 211))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_logsClear.setFont(font)
        self.pushButton_logsClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_logsClear.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border-radius: 1px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    image: url(\"C:/Users/bedir/OneDrive/Masaüstü/icon/22.png\");\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    image: url(\"C:/Users/bedir/OneDrive/Masaüstü/icon/23.png\");\n"
"    }")
        self.pushButton_logsClear.setText("")
        self.pushButton_logsClear.setObjectName("pushButton_logsClear")
        self.label_logsClear = QtWidgets.QLabel(self.tab_logs)
        self.label_logsClear.setGeometry(QtCore.QRect(460, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_logsClear.setFont(font)
        self.label_logsClear.setStyleSheet("color: white;")
        self.label_logsClear.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logsClear.setObjectName("label_logsClear")
        self.label_logsTitle = QtWidgets.QLabel(self.tab_logs)
        self.label_logsTitle.setGeometry(QtCore.QRect(70, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logsTitle.setFont(font)
        self.label_logsTitle.setStyleSheet("color: white;")
        self.label_logsTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logsTitle.setObjectName("label_logsTitle")
        self.textBrowser_logsContent = QtWidgets.QTextBrowser(self.tab_logs)
        self.textBrowser_logsContent.setEnabled(False)
        self.textBrowser_logsContent.setGeometry(QtCore.QRect(30, 50, 221, 251))
        self.textBrowser_logsContent.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgba(255, 255, 255, 255);")
        self.textBrowser_logsContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_logsContent.setObjectName("textBrowser_logsContent")
        self.label_logs.raise_()
        self.label_logsAlpha.raise_()
        self.label_logsClear.raise_()
        self.label_logsTitle.raise_()
        self.pushButton_logsClear.raise_()
        self.textBrowser_logsContent.raise_()
        self.tabWidget_cmail.addTab(self.tab_logs, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.checkBox_notification = QtWidgets.QCheckBox(self.tab_settings)
        self.checkBox_notification.setGeometry(QtCore.QRect(350, 190, 141, 31))
        self.checkBox_notification.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.checkBox_notification.setChecked(True)
        self.checkBox_notification.setObjectName("checkBox_notification")
        self.checkBox_deleteInfo = QtWidgets.QCheckBox(self.tab_settings)
        self.checkBox_deleteInfo.setGeometry(QtCore.QRect(350, 230, 151, 31))
        self.checkBox_deleteInfo.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.checkBox_deleteInfo.setObjectName("checkBox_deleteInfo")
        self.label_settings = QtWidgets.QLabel(self.tab_settings)
        self.label_settings.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_settings.setStyleSheet("border-image:url(\"C:/Users/bedir/PycharmProjects/CMail/images/settings.jpg\");\n"
"border-radius:10px;")
        self.label_settings.setText("")
        self.label_settings.setObjectName("label_settings")
        self.groupBox_Clean = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox_Clean.setGeometry(QtCore.QRect(330, 20, 251, 151))
        self.groupBox_Clean.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.groupBox_Clean.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Clean.setObjectName("groupBox_Clean")
        self.pushButton_deleteInfo = QtWidgets.QPushButton(self.groupBox_Clean)
        self.pushButton_deleteInfo.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.pushButton_deleteInfo.setStyleSheet("color: rgba(0, 0, 0, 255);")
        self.pushButton_deleteInfo.setObjectName("pushButton_deleteInfo")
        self.pushButton_deleteAll = QtWidgets.QPushButton(self.groupBox_Clean)
        self.pushButton_deleteAll.setGeometry(QtCore.QRect(40, 90, 181, 31))
        self.pushButton_deleteAll.setStyleSheet("color:rgba(0, 0, 0, 255);")
        self.pushButton_deleteAll.setObjectName("pushButton_deleteAll")
        self.pushButton_exit = QtWidgets.QPushButton(self.tab_settings)
        self.pushButton_exit.setGeometry(QtCore.QRect(120, 290, 131, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_settigsAlpha = QtWidgets.QLabel(self.tab_settings)
        self.label_settigsAlpha.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_settigsAlpha.setStyleSheet("background-color:rgba(0,0,0,70);\n"
"border-radius:10px;")
        self.label_settigsAlpha.setText("")
        self.label_settigsAlpha.setObjectName("label_settigsAlpha")
        self.groupBox_service = QtWidgets.QGroupBox(self.tab_settings)
        self.groupBox_service.setGeometry(QtCore.QRect(40, 20, 221, 181))
        self.groupBox_service.setStyleSheet("color: rgba(255, 255, 255, 255);")
        self.groupBox_service.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_service.setObjectName("groupBox_service")
        self.label_smtpProtocol = QtWidgets.QLabel(self.groupBox_service)
        self.label_smtpProtocol.setGeometry(QtCore.QRect(0, 80, 91, 16))
        self.label_smtpProtocol.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.label_smtpProtocol.setAlignment(QtCore.Qt.AlignCenter)
        self.label_smtpProtocol.setObjectName("label_smtpProtocol")
        self.lineEdit_imap = QtWidgets.QLineEdit(self.groupBox_service)
        self.lineEdit_imap.setEnabled(False)
        self.lineEdit_imap.setGeometry(QtCore.QRect(90, 50, 111, 20))
        self.lineEdit_imap.setStyleSheet("color: rgba(0 ,0, 0, 255);\n"
"border-radius: 10px;")
        self.lineEdit_imap.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_imap.setObjectName("lineEdit_imap")
        self.lineEdit_smtpProtocol = QtWidgets.QLineEdit(self.groupBox_service)
        self.lineEdit_smtpProtocol.setEnabled(False)
        self.lineEdit_smtpProtocol.setGeometry(QtCore.QRect(90, 80, 111, 20))
        self.lineEdit_smtpProtocol.setStyleSheet("color: rgba(0 ,0, 0, 255);\n"
"border-radius: 10px;")
        self.lineEdit_smtpProtocol.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_smtpProtocol.setObjectName("lineEdit_smtpProtocol")
        self.label_smtpPort = QtWidgets.QLabel(self.groupBox_service)
        self.label_smtpPort.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_smtpPort.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.label_smtpPort.setAlignment(QtCore.Qt.AlignCenter)
        self.label_smtpPort.setObjectName("label_smtpPort")
        self.lineEdit_smtpPort = QtWidgets.QLineEdit(self.groupBox_service)
        self.lineEdit_smtpPort.setEnabled(False)
        self.lineEdit_smtpPort.setGeometry(QtCore.QRect(90, 110, 71, 20))
        self.lineEdit_smtpPort.setStyleSheet("color: rgba(0 ,0, 0, 255);\n"
"border-radius: 10px;")
        self.lineEdit_smtpPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_smtpPort.setObjectName("lineEdit_smtpPort")
        self.label_imap = QtWidgets.QLabel(self.groupBox_service)
        self.label_imap.setGeometry(QtCore.QRect(0, 50, 91, 21))
        self.label_imap.setStyleSheet("color:rgba(255, 255, 255, 255);")
        self.label_imap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imap.setObjectName("label_imap")
        self.checkBox_checkService = QtWidgets.QCheckBox(self.groupBox_service)
        self.checkBox_checkService.setGeometry(QtCore.QRect(50, 20, 121, 18))
        self.checkBox_checkService.setObjectName("checkBox_checkService")
        self.pushButton_confirmServices = QtWidgets.QPushButton(self.groupBox_service)
        self.pushButton_confirmServices.setGeometry(QtCore.QRect(50, 150, 121, 23))
        self.pushButton_confirmServices.setStyleSheet("color: rgba(0 ,0, 0, 255);")
        self.pushButton_confirmServices.setObjectName("pushButton_confirmServices")
        self.pushButton_background = QtWidgets.QPushButton(self.tab_settings)
        self.pushButton_background.setGeometry(QtCore.QRect(420, 280, 181, 31))
        self.pushButton_background.setObjectName("pushButton_background")
        self.label_settings.raise_()
        self.label_settigsAlpha.raise_()
        self.checkBox_notification.raise_()
        self.checkBox_deleteInfo.raise_()
        self.groupBox_Clean.raise_()
        self.pushButton_exit.raise_()
        self.groupBox_service.raise_()
        self.pushButton_background.raise_()
        self.tabWidget_cmail.addTab(self.tab_settings, "")
        self.tab_aboutMe = QtWidgets.QWidget()
        self.tab_aboutMe.setObjectName("tab_aboutMe")
        self.label_aboutMeAlpha = QtWidgets.QLabel(self.tab_aboutMe)
        self.label_aboutMeAlpha.setGeometry(QtCore.QRect(150, -1, 351, 331))
        self.label_aboutMeAlpha.setStyleSheet("background-color:rgba(0,0,0,80);\n"
"border-radius:10px;")
        self.label_aboutMeAlpha.setText("")
        self.label_aboutMeAlpha.setObjectName("label_aboutMeAlpha")
        self.label_author = QtWidgets.QLabel(self.tab_aboutMe)
        self.label_author.setGeometry(QtCore.QRect(240, 70, 161, 81))
        self.label_author.setStyleSheet("color:white;\n"
"border-radius:10px;")
        self.label_author.setObjectName("label_author")
        self.label_aboutMe = QtWidgets.QLabel(self.tab_aboutMe)
        self.label_aboutMe.setGeometry(QtCore.QRect(0, 0, 631, 331))
        self.label_aboutMe.setStyleSheet("border-image:url(\"C:/Users/bedir/PycharmProjects/CMail/images/about_me.jpg\");\n"
"border-radius:10px;")
        self.label_aboutMe.setText("")
        self.label_aboutMe.setObjectName("label_aboutMe")
        self.label_rights = QtWidgets.QLabel(self.tab_aboutMe)
        self.label_rights.setGeometry(QtCore.QRect(260, 300, 131, 21))
        self.label_rights.setStyleSheet("color:white;\n"
"border-radius:10px;")
        self.label_rights.setObjectName("label_rights")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_aboutMe)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 160, 239, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_contact = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_contact.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_contact.setObjectName("horizontalLayout_contact")
        self.pushButton_linkedIn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.pushButton_linkedIn.setFont(font)
        self.pushButton_linkedIn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: rgba(85, 98, 112, 255);\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(131, 96, 53, 255);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    }")
        self.pushButton_linkedIn.setObjectName("pushButton_linkedIn")
        self.horizontalLayout_contact.addWidget(self.pushButton_linkedIn)
        self.pushButton_gitHub = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.pushButton_gitHub.setFont(font)
        self.pushButton_gitHub.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: rgba(85, 98, 112, 255);\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(131, 96, 53, 255);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    }")
        self.pushButton_gitHub.setObjectName("pushButton_gitHub")
        self.horizontalLayout_contact.addWidget(self.pushButton_gitHub)
        self.pushButton_mail = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.pushButton_mail.setFont(font)
        self.pushButton_mail.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: rgba(85, 98, 112, 255);\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(131, 96, 53, 255);\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    }")
        self.pushButton_mail.setObjectName("pushButton_mail")
        self.horizontalLayout_contact.addWidget(self.pushButton_mail)
        self.label_aboutMe.raise_()
        self.label_aboutMeAlpha.raise_()
        self.label_author.raise_()
        self.label_rights.raise_()
        self.horizontalLayoutWidget.raise_()
        self.tabWidget_cmail.addTab(self.tab_aboutMe, "")

        self.retranslateUi(Form_cmail)
        self.tabWidget_cmail.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_cmail)

    def retranslateUi(self, Form_cmail):
        _translate = QtCore.QCoreApplication.translate
        Form_cmail.setWindowTitle(_translate("Form_cmail", "Cmail"))
        self.label_homeTitle.setText(_translate("Form_cmail", "<html><head/><body><p align=\"center\">How to Work?</p></body></html>"))
        self.textBrowser_homeContent.setHtml(_translate("Form_cmail", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">Cmail (Confirmed Mail), protects you from phishing attacks by confirming that incoming mails are from the original source.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ Cmail starts to seek your mail address when you click on &quot;Start&quot;,</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ If you got a new mail, Cmail creates an instant response mail.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ The response mail includes an information text and a unique code.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ Sender should reply the response mail with the unique code.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ Note that, sender can add any information to reply mail.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ When sender replies the response mail, you got Confirmed Mail.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">+ If Confirmed Mail includes the unique code, original mail is marked.</span></p></body></html>"))
        self.tabWidget_cmail.setTabText(self.tabWidget_cmail.indexOf(self.tab_home), _translate("Form_cmail", "Home"))
        self.pushButton_start.setText(_translate("Form_cmail", "Start"))
        self.pushButton_stop.setText(_translate("Form_cmail", "Stop"))
        self.lineEdit_mail.setPlaceholderText(_translate("Form_cmail", "Mail address"))
        self.lineEdit_password.setPlaceholderText(_translate("Form_cmail", "Password"))
        self.label_checkMsg.setText(_translate("Form_cmail", "Incorrect Mail Format"))
        self.label_status.setText(_translate("Form_cmail", "Click on Start"))
        self.label_cmailTitle.setText(_translate("Form_cmail", "Confirmed Mail"))
        self.textBrowser_homeContent_2.setHtml(_translate("Form_cmail", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">Make your own settings, Cmail will take care of the rest for you:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">- If you don\'t use gmail: &quot;Settings&quot; -&gt; &quot;Service Adjusting&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">- Disable notifications: &quot;Settings&quot; -&gt; &quot;Show notifications&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">- Delete read Confirmed Mail: &quot;Settings&quot; -&gt; &quot;Delete read info mail&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans MS\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">- To clear your inbox: &quot;Settings&quot; -&gt; &quot;Inbox Cleaning&quot; category</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Log records can be seen in &quot;Logs&quot; section.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- To clear log history: &quot;Logs&quot; -&gt; &quot;Clear Logs&quot;</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">After making your own settings,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans MS\';\">You are ready to use Cmail!</span></p></body></html>"))
        self.label_homeTitle_2.setText(_translate("Form_cmail", "<html><head/><body><p align=\"center\">User Guide</p></body></html>"))
        self.tabWidget_cmail.setTabText(self.tabWidget_cmail.indexOf(self.tab_cmail), _translate("Form_cmail", "Confirmed Mail"))
        self.label_logsClear.setText(_translate("Form_cmail", "Clear Logs"))
        self.label_logsTitle.setText(_translate("Form_cmail", "History Logs"))
        self.tabWidget_cmail.setTabText(self.tabWidget_cmail.indexOf(self.tab_logs), _translate("Form_cmail", "Logs"))
        self.checkBox_notification.setText(_translate("Form_cmail", "Show notifications"))
        self.checkBox_deleteInfo.setText(_translate("Form_cmail", "Delete read info mail"))
        self.groupBox_Clean.setTitle(_translate("Form_cmail", "Inbox Cleaning"))
        self.pushButton_deleteInfo.setToolTip(_translate("Form_cmail", "Delete \"Confirmed Mails\""))
        self.pushButton_deleteInfo.setText(_translate("Form_cmail", "Clear information mails"))
        self.pushButton_deleteAll.setToolTip(_translate("Form_cmail", "Delete all mails except confirmed ones"))
        self.pushButton_deleteAll.setText(_translate("Form_cmail", "Clear not confirmed mails"))
        self.pushButton_exit.setText(_translate("Form_cmail", "Exit Cmail"))
        self.groupBox_service.setTitle(_translate("Form_cmail", "Service Adjusting"))
        self.label_smtpProtocol.setText(_translate("Form_cmail", "SMTP Protocol:"))
        self.lineEdit_imap.setText(_translate("Form_cmail", "imap.gmail.com"))
        self.lineEdit_smtpProtocol.setText(_translate("Form_cmail", "smtp.gmail.com"))
        self.label_smtpPort.setText(_translate("Form_cmail", "SMTP Port:"))
        self.lineEdit_smtpPort.setText(_translate("Form_cmail", "587"))
        self.label_imap.setText(_translate("Form_cmail", "IMAP Protocol:"))
        self.checkBox_checkService.setText(_translate("Form_cmail", "I don\'t use Gmail"))
        self.pushButton_confirmServices.setText(_translate("Form_cmail", "Confirm"))
        self.pushButton_background.setToolTip(_translate("Form_cmail", "Minimize Cmail to tray menu"))
        self.pushButton_background.setText(_translate("Form_cmail", "Run in background"))
        self.tabWidget_cmail.setTabText(self.tabWidget_cmail.indexOf(self.tab_settings), _translate("Form_cmail", "Settings"))
        self.label_author.setText(_translate("Form_cmail", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic;\">Developed by</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Bedirhan BUDAK</span></p><p align=\"center\"><span style=\" font-size:10pt; font-style:italic;\">as the Graduation Project</span></p></body></html>"))
        self.label_rights.setText(_translate("Form_cmail", "<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">All rights reserved ©</span></p></body></html>"))
        self.pushButton_linkedIn.setText(_translate("Form_cmail", "C"))
        self.pushButton_gitHub.setText(_translate("Form_cmail", ")"))
        self.pushButton_mail.setText(_translate("Form_cmail", "k"))
        self.tabWidget_cmail.setTabText(self.tabWidget_cmail.indexOf(self.tab_aboutMe), _translate("Form_cmail", "About Me"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_cmail = QtWidgets.QWidget()
    ui = Ui_Form_cmail()
    ui.setupUi(Form_cmail)
    Form_cmail.show()
    sys.exit(app.exec_())
